export const defaultLanguage = {
  English: {
    same: {
      email: 'Email',
      password: 'Password',
      fullName: 'Full Name',
      confirmPassword: 'Confirm Password',
      phone: 'Phone',
      buttonCancel: 'Cancel',
      buttonOK: 'OK',
      buttonSave: 'Save',
      lang: 'en',
      feedback: 'Feedback',
      language: 'English',
    },
    navigation: {
      signIn: 'Sign In',
      forgotPass: 'Forgot Password',
      signUp: 'Sign Up',
      home: 'Home',
      download: 'Download',
      browse: 'Browse',
      profile: 'Profile',
      search: 'Search',
      accountManagement: 'Account Management',
    },
    login: {
      loginSuccess: 'Login successful',
      loginFail: 'Email or password wrong!',
      alertInternet: 'You need connect to internet to sign in!',
      buttonSignIn: 'SIGN IN',
      buttonSignInWithGoogle: 'SIGN IN WITH GOOGLE',
      buttonForgot: 'FORGOT PASSWORD',
      buttonSignUp: 'SIGN UP FREE',
      buttonGuestJoin: 'JOIN AS GUEST'
    },
    forgotPass: {
      title: 'Forgot Password',
      success: 'Email has been sent',
      fail: 'Email address does not exist!',
      description: "Enter your email address and we'll send you a link to reset your password",
      buttonSend: 'Send Email',
    },
    signUp: {
      title: 'Create your account',
      fail: 'Email or phone already exist!',
      success: 'Registration complete successfully!',
      description: 'Please check your registered email for email verification',
      password: 'Password* (8-20 characters)',
      emailError: 'Invalid email!',
      fullNameError1: 'Name cannot contain numbers or special characters like #,%, $,...!',
      fullNameError2: 'Please type your full name!',
      passwordError: 'Password must be between 8 and 20 characters!',
      passwordConfirmError: 'Password and Confirm Password do not match!',
      phoneError: 'Please enter a valid phone number!',
      require: '* Required field',
      checkBox: 'By checking here and continuing, I agree to the ',
      term: 'Terms of Use.',
      termError: 'Please check Terms of Use!',
      buttonCreate: 'Create Account'
    },
    home: {
      new: 'New Course',
      recommend: 'Recommended Courses',
      continue: 'Continue learning',
      favorite: 'Favorite courses',
      channels: 'Channels',
      description: "Let's get you started",
      browse: 'Browse new & popular courses',
      search: 'Search the library',
      buttonSignIn: 'SIGN IN',
      sectionCourse: {
        seeAll: ' See more > ',
      }
    },
    courseDropDownButton: {
      favorite: 'Favorite',
      unFavorite: 'UnFavorite',
      addChannel: 'Add to channel',
      remove: 'Remove',
    },
    channelDialog: {
      added: 'added',
      addChannel: 'Add to Channel',
      buttonNewChannel: '  New channel',
      createChannel: 'Create channel',
      channelTitle: 'Channel title',
    },
    courseDetail: {
      downloadError: 'Something wrong! Please try again later',
      titleTab: {
        course: 'Course',
        lessons: 'Lessons',
        transcript: 'Transcript'
      },
      generalDetail: {
        payment: 'Payment',
        favorite: 'Favorite',
        unFavorite: 'UnFavorite',
        channel: 'Channel',
        share: 'Share',
        download: 'Download',
        description: 'Description: ',
        requirement: 'Requirement: ',
        learnWhat: 'Learn what: ',
        rating: 'Rating course',
        check: 'Take a learning check',
        courseLike: 'Courses like category'
      },
      lessonItemOverview: 'Course Overview',
      video: {
        error: 'Something went wrong!!!',
        continue: 'Continue your progress with this lesson?',
      },
      infoDialog: {
        content: "This course isn't included with your current subscription.",
      }
    },
    channelDetail: {
      process: 'Your Process: ',
      courseInChannel: 'Courses in channel',
    },
    authorDetail: {
      intro: 'Intro',
      skill: 'Skill',
      contact: 'Contact',
      course: 'Course',
      waitUpdate: '(Waiting for an update)',
    },
    profile: {
      favoriteCategories: 'Favorite Categories',
      change: 'Change',
      buttonChooseFavorite: 'Choose your favorite categories',
      user: 'User',
      type: 'TYPE: ',
      point: 'POINT: ',
      createAt: 'CREATE AT: ',
      lastUpdate: 'LAST UPDATE: ',
      alertSignIn: 'Please sign in to view your profile',
      signIn: 'SIGN IN',
      chooseFavorite: {
        title: 'Select favorite categories',
        note: '(Please select at least one category)',
        select: 'Select',
      }
    },
    mainScreenHeader: {
      setting: 'Setting',
      sendFeedback: 'Send Feedback',
      signOut: 'Sign Out',
      signIn: 'Sign In',
    },
    categoryDetail: {
      new: 'New in ',
      trend: 'Trending in ',
    },
    sendFeedback: {
      success: 'Success! Your feedback has been sent.',
      fail: 'Something went wrong! Please try again. ',
      feedback: 'Feedback',
      subject: 'Subject',
      note: 'Please write something!',
      content: 'Content',
      send: 'Send',
    },
    payment: {
      success: 'Payment Success',
      successNote: 'Thank you for using our services!',
      buttonHome: 'Home',
      buttonCourse: 'Course',
      payment: 'Payment',
      course: 'Course Detail: ',
      free: 'Free',
      user: 'User Detail: ',
    },
    download: {
      empty: 'No Download',
      refresh: 'Refresh',
    },
    browse: {
      newReleases: 'New Releases',
      recommended: 'Recommended For You',
      buttonNewReleases: `NEW\nRELEASES`,
      buttonRecommended: `RECOMMENDED\nFOR YOU`,
      category: 'Category',
      topAuthor: 'Top Authors',
    },
    search: {
      placeholder: 'Search',
      recentSearches: 'Recent searches',
      favoriteCategories: 'Your Favorite Categories',
      clear: ' Clear ',
      all: 'All',
      courses: 'Courses',
      course: 'Course',
      authors: 'Authors',
      author: 'Author',
      noResult: "Sorry, we couldn't find any matches for ",
      titleFilter: {
        newest: 'Newest',
        oldest: 'Oldest',
        priceIncrease1: 'Price increase',
        priceIncrease2: 'Price (Low-High)',
        priceDecrease1: 'Price decrease',
        priceDecrease2: 'Price (High-Low)',
        bestSell: 'Best Seller',
        selectFilter: 'Select Filter   ',
        price: 'Price'
      },
      selectFilterModal: {
        free: 'Free',
        selectFilter: 'Select Filter',
        category: 'Category',
        time: 'Time',
        price: 'Price',
      },
    },
    accountManagement: {
      profile: 'Profile',
      account: 'Account',
      theme: 'Theme',
      light: 'Light',
      dark: 'Dark',
      sendFeedback: 'Send Feedback',
      appVersion: 'App Version',
      signOut: 'Sign Out',
      language: 'Language'
    },
    account: {
      changeEmailSuccess: 'Change email success!',
      yourAccount: 'Your Account',
      avatarLink: 'Avatar link',
      fullName: 'Full name',
      fullNameError: 'Name cannot contain numbers or special characters like #,%, $, ...!',
      phone: 'Phone',
      phoneError: 'Please enter a valid phone number!',
      updateAccount: 'Update Account',
      emailAddress: 'Email address',
      emailNote1: 'If you change your email, your account will be logged out and deactivated until you confirm new email.',
      emailNote2: 'Other account information such as courses you like, payment history, course history, etc. will remain the same.',
      email: 'Email:',
      emailError: 'Invalid email!',
      changeEmail: 'Change Email',
      password: 'Password',
      currentPassword: 'Current password',
      passwordError1: 'Password must be between 8 and 20 characters!',
      newPassword: 'New password',
      passwordError2: 'Your new password cannot be the same as your current password',
      confirmPassword: 'Confirm password',
      passwordError3: 'Password and Confirm Password do not match!',
      update: 'Update',
      updateProfileSuccess: 'Success! Your profile has beeen changed!',
      updatePasswordSuccess: 'Success! Your password has beeen changed!',
      updateEmailSuccess: 'Success! Your email has beeen changed!',
    },
  },
  Vietnamese: {
    same: {
      email: 'Email',
      password: 'Mật khẩu',
      fullName: 'Họ tên',
      confirmPassword: 'Xác nhận mật khẩu',
      phone: 'Số điện thoại',
      buttonCancel: 'Hủy',
      buttonOK: 'Đồng ý',
      buttonSave: 'Lưu',
      lang: 'vi',
      feedback: 'Phản hồi',
      language: 'Tiếng Việt',
    },
    navigation: {
      signIn: 'Đăng nhập',
      forgotPass: 'Quên mật khẩu',
      signUp: 'Đăng ký',
      home: 'Trang chính',
      download: 'Tải',
      browse: 'Duyệt',
      profile: 'Thông tin',
      search: 'Tìm kiếm',
      accountManagement: 'Quản lý tài khoản',
    },
    login: {
      loginSuccess: 'Đăng nhập thành công',
      loginFail: 'Email hoặc mật khẩu sai!',
      alertInternet: 'Bạn cần kết nối mạng để đăng nhập',
      buttonSignIn: 'ĐĂNG NHẬP',
      buttonSignInWithGoogle: 'ĐĂNG NHẬP VỚI GOOGLE',
      buttonForgot: 'QUÊN MẬT KHẨU',
      buttonSignUp: 'ĐĂNG KÝ',
      buttonGuestJoin: 'XEM TRƯỚC',
    },
    forgotPass: {
      title: 'QUÊN MẬT KHẨU',
      success: 'Email đã được gửi',
      fail: 'Địa chỉ email không tồn tại!',
      description: "Nhập địa chỉ email của bạn và chúng tôi sẽ gửi đường dẫn để bạn thiệt lập lại mật khẩu",
      buttonSend: 'Gửi Email',
    },
    signUp: {
      title: 'Tạo tài khoản của bạn',
      fail: 'Email hoặc số điện thoại đã tồn tại!',
      success: 'Đăng ký thành công!',
      description: 'Vui lòng kiểm tra email bạn đã đăng ký để xác minh email',
      password: 'Mật khẩu* (8-20 kí tự)',
      emailError: 'Email không hợp lệ!',
      fullNameError1: 'Tên không chứa số và kí tự đặc biệt như #,%, $,...!',
      fullNameError2: 'Vui lòng nhập họ tên của bạn!',
      passwordError: 'Mật khẩu phải từ 8 đến 20 kí tự!',
      passwordConfirmError: 'Mật khẩu và mật khẩu xác nhận không khớp!',
      phoneError: 'Vui lòng nhập số điện thoại hợp lệ!',
      require: '* Bắt buộc',
      checkBox: 'Bằng việc chọn và tiếp tục, tôi đồng ý với ',
      term: 'Điều khoản sử dụng.',
      termError: 'Vui lòng chọn chấp nhận Điều khoản sử dụng!',
      buttonCreate: 'Tạo tài khoản',
    },
    home: {
      new: 'Khóa học mới',
      recommend: 'Khóa học bạn có thể thích',
      continue: 'Tiếp tục học',
      favorite: 'Khóa học yêu thích',
      channels: 'Kênh',
      description: "Bắt đầu",
      browse: 'Khóa học mới và phổ biến',
      search: 'Tìm kiếm khóa học',
      buttonSignIn: 'Đăng nhập',
      sectionCourse: {
        seeAll: ' Xem thêm > ',
      }
    },
    courseDropDownButton: {
      favorite: 'Thích',
      unFavorite: 'Không thích',
      addChannel: 'Thêm vào kênh',
      remove: 'Bỏ',
    },
    channelDialog: {
      added: '(đã thêm)',
      addChannel: 'Thêm vào Kênh',
      buttonNewChannel: '  Kênh mới',
      createChannel: 'Tạo kênh',
      channelTitle: 'Tên kênh',
    },
    courseDetail: {
      downloadError: 'Có lỗi đã xảy ra! Vui lòng thử lại sau',
      titleTab: {
        course: 'Khóa học',
        lessons: 'Bài học',
        transcript: 'Phụ đề',
      },
      generalDetail: {
        payment: 'Thanh toán',
        favorite: 'Thích',
        unFavorite: 'Không thích',
        channel: 'Kênh',
        share: 'Chia sẻ',
        download: 'Tải',
        description: 'Mô tả: ',
        requirement: 'Yêu cầu: ',
        learnWhat: 'Học về: ',
        rating: 'Đánh giá khóa học',
        check: 'Bài tập',
        courseLike: 'Khóa cùng chủ đề',
      },
      lessonItemOverview: 'Giới thiệu khóa học',
      video: {
        error: 'Có lỗi đã xảy ra!!!',
        continue: 'Tiếp tục tiến trình học trước đó của bạn?',
      },
      infoDialog: {
        content: "Bạn vui lòng mua khóa học để sủ dụng chức năng này.",
      },
    },
    channelDetail: {
      process: 'Tiến trình học: ',
      courseInChannel: 'Khóa học trong kênh',
    },
    authorDetail: {
      intro: 'Thông tin',
      skill: 'Kĩ năng',
      contact: 'Liên hệ',
      course: 'Khóa học',
      waitUpdate: '(Vui lòng đợi cập nhật)',
    },
    profile: {
      favoriteCategories: 'Lĩnh vực thích',
      change: 'Thay đổi',
      buttonChooseFavorite: 'Chọn lĩnh vực bạn thích',
      user: 'Người dùng',
      type: 'LOẠI: ',
      point: 'ĐIỂM: ',
      createAt: 'TẠO LÚC: ',
      lastUpdate: 'CẬP NHẬT LẦN CUỐI: ',
      alertSignIn: 'Vui lòng đăng nhập để xem',
      signIn: 'ĐĂNG NHẬP',
      chooseFavorite: {
        title: 'Lựa chọn lĩnh vực thích',
        note: '(Vui lòng chọn ít nhất một lĩnh vực)',
        select: 'Chọn',
      }
    },
    mainScreenHeader: {
      setting: 'Cài đặt',
      sendFeedback: 'Gửi phản hồi',
      signOut: 'Đăng xuất',
      signIn: 'Đăng nhập',
    },
    categoryDetail: {
      new: 'Mới trong ',
      trend: 'Xu hướng trong ',
    },
    sendFeedback: {
      success: 'Thành công! Phản hồi của bạn đã được gửi.',
      fail: 'Có lỗi xảy ra! Vui lòng thử lại sau. ',
      feedback: 'Phản hồi',
      subject: 'Chủ đề',
      note: 'Vui lòng không bỏ trống!',
      content: 'Nội dung',
      send: 'Gửi',
    },
    payment: {
      success: 'Thanh toán thành công',
      successNote: 'Cảm ơn bạn đã sử dụng dịch vụ của chúng tôi!',
      buttonHome: 'Màn hình chính',
      buttonCourse: 'Khóa học',
      payment: 'Thanh toán',
      course: 'Thông tin khóa học: ',
      free: 'Miễn phí',
      user: 'Thông tin người dùng: ',
    },
    download: {
      empty: 'Chưa tải khóa học',
      refresh: 'Tải lại dữ liệu',
    },
    browse: {
      newReleases: 'Mới cập nhật',
      recommended: 'Đề xuất cho bạn',
      buttonNewReleases: `MỚI\nCẬP NHẬT`,
      buttonRecommended: `ĐỀ XUẤT\nCHO BẠN`,
      category: 'Lĩnh vực',
      topAuthor: 'Giáo viên hàng đầu',
    },
    search: {
      placeholder: 'Tìm kiếm',
      recentSearches: 'Tìm kiếm gần đây',
      favoriteCategories: 'Các lĩnh vực thích',
      clear: ' Xóa ',
      all: 'Tất cả',
      courses: 'Khóa học',
      course: 'Khóa học',
      authors: 'Giáo viên',
      author: 'Giáo viên',
      noResult: "Không tìm thấy kết quả nào cho ",
      titleFilter: {
        newest: 'Mới nhất',
        oldest: 'Cũ nhất',
        priceIncrease1: 'Giá tăng',
        priceIncrease2: 'Giá (Thấp-Cao)',
        priceDecrease1: 'Giá giảm',
        priceDecrease2: 'Giá (Cao-Thấp)',
        bestSell: 'Bán nhiều',
        selectFilter: 'Bộ lọc   ',
        price: 'Giá'
      },
      selectFilterModal: {
        free: 'Miễn phí',
        selectFilter: 'Bộ lọc',
        category: 'Lĩnh vực',
        time: 'Thời gian',
        price: 'Giá',
      },
    },
    accountManagement: {
      profile: 'Thông tin',
      account: 'Tài khoản',
      theme: 'Màu Nền',
      light: 'Sáng',
      dark: 'Tối',
      sendFeedback: 'Gửi phản hồi',
      appVersion: 'Phiên bản ứng dụng',
      signOut: 'Đăng xuất',
      language: 'Ngôn ngữ'
    },
    account: {
      changeEmailSuccess: 'Đổi email thành công!',
      yourAccount: 'Tài khoản',
      avatarLink: 'Liên kết ảnh',
      fullName: 'Họ tên',
      fullNameError: 'Tên không chứa số và kí tự đặc biệt như #,%, $,...!',
      phone: 'Số điện thoại',
      phoneError: 'Vui lòng nhập số điện thoại hợp lệ!',
      updateAccount: 'Cập nhật tài khoản',
      emailAddress: 'Địa chỉ email',
      emailNote1: 'Nếu bạn thay đổi email, tài khoản của bạn sẽ đăng xuất và không hoạt động đến khi bạn kích hoạt đường dẫn được gửi đến email mới',
      emailNote2: 'Các thông tin tài khoản như khóa học thích, lịch sử thanh toán, lịch sử khóa học, .... sẽ giữ như cũ.',
      email: 'Email:',
      emailError: 'Email không hợp lệ!',
      changeEmail: 'Đổi Email',
      password: 'Mật khẩu',
      currentPassword: 'Mật khẩu hiện tại',
      passwordError1: 'Mật khẩu phải từ 8 đến 20 kí tự!',
      newPassword: 'Mật khẩu mới',
      passwordError2: 'Mật khẩu mới phải khác với mật khẩu hiện tại!',
      confirmPassword: 'Xác nhận mật khẩu',
      passwordError3: 'Mật khẩu và mật khẩu xác nhận không khớp!',
      update: 'Cập nhật',
      updateProfileSuccess: 'Thành công! Thông tin tài khoản đã thay đổi!',
      updatePasswordSuccess: 'Thành công! Mật khẩu của bạn đã thay đổi!',
      updateEmailSuccess: 'Thành công! Email của bạn đã thay đổi!',

    },
  }
}